// Field-only views share the existing shell, permission model, and retry handling.
export function createWorkspace(ctx) {
  const {$,e,n,state,api,write,reload,notice,sheet:baseSheet,closeSheet,header,empty,jobHref,jobRow,actionButton,fmt,taskOptions} = ctx;
  const sheet = (title,html) => {baseSheet(title,html);const form=$('#sheet-body form');if(form)form.dataset.ticketId=String(state.job?.ticket_id||0);};
  const button = (action,text,attrs='',secondary=true) => actionButton('workspace-'+action,e(text),attrs,secondary);
  const options = (values,selected,blank=false) => (blank?'<option value="">Choose…</option>':'')+Object.entries(values||{}).map(([value,label])=>`<option value="${e(value)}" ${String(value)===String(selected)?'selected':''}>${e(label)}</option>`).join('');
  const choices = (rows,id,name,selected,zero='Not set') => `<option value="0">${e(zero)}</option>`+(rows||[]).map(row=>`<option value="${n(row[id])}" ${n(selected)===n(row[id])?'selected':''}>${e(row[name])}</option>`).join('');
  const input = (title,name,value='',extra='') => `<label>${title}<input name="${name}" value="${e(value)}" ${extra}></label>`;
  const text = (title,name,value='',extra='') => `<label>${title}<textarea name="${name}" aria-label="${e(title)}" ${extra}>${e(value)}</textarea></label>`;
  const local = value => {if(!value)return '';const d=new Date(value);return new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
  let secretVersion=0, secretTimer, search={q:'',scope:'mine',state:'open',client_id:0}, searchResult=null, newClient=null;
  let asset=null, historyNext=null, fileNext=null, activeDocument=0;

  function clearSecrets() {
    secretVersion++; clearTimeout(secretTimer);
    if($('#credential-secret')) { $('#sheet-body').replaceChildren(); $('#sheet').close(); state.coveredSheet=false; }
  }
  function historyRows(entries) {
    return entries.map(row=>`<article class="list-row"><div class="row-main"><div class="note-meta"><strong>${e(row.author||row.user_name||'System')}</strong><span>${e(fmt(row.ticket_reply_created_at))}</span><span class="tag">${e(row.ticket_reply_type)}</span>${row.ticket_reply_time_worked&&row.ticket_reply_time_worked!=='00:00:00'?`<span>${e(row.ticket_reply_time_worked)} worked</span>`:''}</div><p class="prose">${e(row.ticket_reply)}</p></div></article>`).join('');
  }
  function communication(j) {
    const history=j.history||{entries:j.notes||[],next:null}; historyNext=history.next;
    return `<div class="section-head"><h2>Conversation and time</h2>${!j.terminal&&state.boot.user.write?`<div class="actions">${button('reply','Write an update','',false)}${button('time','Add manual time')}</div>`:''}</div><p class="hint">Internal notes, customer replies, and time entries share the ticket history. Each entry shows its visibility.</p><div id="history-list" class="list">${historyRows(history.entries)||'<p class="hint">No conversation yet.</p>'}</div>${historyNext?button('history-more','Load earlier entries'):''}`;
  }
  function contactRows(contacts) {
    return contacts.map(c=>{const phone=String(c.contact_mobile||c.contact_phone||'').replace(/[^+\d,;#*]/g,'');return `<div class="list-row"><div><h3>${e(c.contact_name)}</h3><p class="muted">${e(c.contact_title||'')}${n(c.contact_primary)?' · Primary contact':''}</p><div class="actions">${phone?`<a class="button secondary" href="tel:${e(phone)}">Call</a>`:''}${c.contact_email?`<a class="button secondary" href="mailto:${e(c.contact_email)}">${e(c.contact_email)}</a>`:''}</div></div></div>`;}).join('')||'<p class="hint">No contacts recorded.</p>';
  }
  function assetRows(assets) {
    return assets.length?`<div class="list">${assets.map(a=>`<div class="list-row"><div class="row-main"><h3>${button('asset',a.asset_name,`data-id="${n(a.asset_id)}"`)}</h3><p class="muted">${e([a.asset_make,a.asset_model,a.asset_serial].filter(Boolean).join(' · '))}</p></div></div>`).join('')}</div>`:empty('No assets found','Search by name or serial number.');
  }
  function resources(j) {
    return `<h2>Client and site resources</h2><section class="subsection"><h3>People</h3><div class="list">${contactRows(j.contacts||[])}</div></section>${state.boot.user.documents?`<section class="subsection"><div class="section-head"><h3>Assets</h3>${actionButton('scan','Scan code','',true)}</div><form id="asset-search" class="search"><input name="q" aria-label="Asset name or serial number" placeholder="Find an asset by name or serial" required maxlength="200"><button>Find</button></form><div id="assets">${assetRows(j.assets)}</div></section><section class="subsection"><h3>Networks</h3>${(j.networks||[]).map(net=>`<details class="resource-details"><summary>${e(net.network_name)} · ${e(net.network)}</summary><dl class="facts"><dt>Gateway</dt><dd>${e(net.network_gateway||'Not recorded')}</dd><dt>Subnet</dt><dd>${e(net.network_subnet||'Not recorded')}</dd><dt>VLAN</dt><dd>${e(net.network_vlan??'Not recorded')}</dd><dt>DNS</dt><dd>${e([net.network_primary_dns,net.network_secondary_dns].filter(Boolean).join(', '))}</dd><dt>DHCP</dt><dd>${e(net.network_dhcp_range||'Not recorded')}</dd></dl><p class="prose">${e(net.network_notes)}</p></details>`).join('')||'<p class="hint">No networks recorded.</p>'}</section>`:''}${state.boot.user.credentials?`<section class="subsection"><h3>Credentials</h3><p class="hint">Reveal only when needed. Credentials clear after 30 seconds, when covered, or when you leave the app.</p><label>Find a credential<input id="credential-search" type="search" placeholder="Search credential names"></label><div class="list" id="credential-list">${(j.credentials||[]).map(c=>`<div class="list-row" data-credential-name="${e(c.credential_name.toLowerCase())}"><div class="row-main"><h3>${e(c.credential_name)}</h3><p class="muted">${e(c.credential_description)}</p></div>${button('credential','Reveal',`data-id="${n(c.credential_id)}"`)}</div>`).join('')||'<p class="hint">No credentials recorded.</p>'}</div></section>`:''}`;
  }
  function jobActions(j) {
    if(!state.boot.user.write)return '';
    if(j.closed)return button('followup','Create follow-up');
    return `<div class="heading-actions">${j.terminal?button('transition','Reopen',`data-kind="reopen"`):button('plan','Manage job')}${button('transition',j.terminal?'Close ticket':'Resolve ticket',`data-kind="${j.terminal?'close':'resolve'}"`,false)}</div>`;
  }
  function approvals(j) {
    return `<div class="section-head"><h2>Approvals</h2>${state.boot.user.write&&!j.terminal?button('approval','Request approval','',false):''}</div><p class="hint">Ticket and task approvals keep their assigned decision makers. Customer approvals are made by the customer.</p><div class="list">${(j.approvals||[]).map(r=>`<article class="list-row"><div class="row-main"><h3>${e(r.task_name)}</h3><p>${e(r.route_label)}</p><p class="hint">${e(r.status)}${r.expires_at&&r.status==='pending'?' · Request expires '+e(fmt(r.expires_at)):''}</p>${state.boot.user.write&&!j.terminal&&r.actionable?`<div class="actions">${r.can_decide?button('approval','Record decision',`data-id="${n(r.id)}" data-kind="${e(r.kind)}" data-operation="decide"`,false):''}${['pending','declined'].includes(r.status)?button('approval','Request again',`data-id="${n(r.id)}" data-kind="${e(r.kind)}" data-operation="retry"`)+button('approval','Change approver',`data-id="${n(r.id)}" data-kind="${e(r.kind)}" data-operation="reroute"`):''}</div>`:''}</div></article>`).join('')||'<p class="hint">No approvals have been requested.</p>'}</div>`;
  }
  function approvalForm(j,b) {
    const r=(j.approvals||[]).find(r=>n(r.id)===n(b.dataset.id)&&r.kind===b.dataset.kind), op=b.dataset.operation||'request';
    const routes={'internal:any':'Any other internal technician','internal:specific':'Specific internal technician','client:any':'Ticket contact','client:manager':'Customer portal manager','client:technical':'Technical contact','client:billing':'Billing contact','client:specific':'Specific client contact'};
    const route=r?r.scope+':'+r.type:'internal:any';
    sheet({request:'Request approval',retry:'Request approval again',reroute:'Change approver',decide:'Record approval decision'}[op],`<form id="workspace-approval-form" class="form-grid"><input type="hidden" name="operation" value="${op}"><input type="hidden" name="approval_id" value="${n(r?.id)}">${r?`<input type="hidden" name="kind" value="${e(r.kind)}"><input type="hidden" name="task_id" value="${n(r.task_id)}"><p><strong>${e(r.task_name)}</strong><br>${e(r.route_label)}</p>`:`<label>Approval for<select name="task_id">${taskOptions(j)}</select></label>`}${op==='decide'?`<label>Decision<select name="decision" required>${options({approved:'Approve',declined:'Decline'},'',true)}</select></label>`:op==='retry'?'<p>A new request goes to the current approver. The previous link will expire.</p>':`<label>Send request to<select name="route">${options(routes,route)}</select></label><label id="approval-user" ${route==='internal:specific'?'':'hidden'}>Internal approver<select name="required_user_id">${choices(j.owners.filter(o=>n(o.user_id)!==n(state.boot.user.id)),'user_id','user_name',r?.required_user_id,'Choose a technician')}</select></label><label id="approval-contact" ${route==='client:specific'?'':'hidden'}>Client approver<select name="required_contact_id">${choices(j.contacts,'contact_id','contact_name',r?.required_contact_id,'Choose a contact')}</select></label>`}${text('Reason','reason','','required maxlength="1000"')}<p class="hint">${op==='decide'?'Your decision and reason are recorded in the approval history.':'Sends the request through the existing approval notification route. You cannot approve your own request.'}</p><button>${op==='decide'?'Save decision':'Send approval request'}</button></form>`);
  }
  function promises(j) {
    return `<section class="subsection"><div class="section-head"><h2>Customer commitments</h2>${state.boot.user.write&&!j.terminal?button('promise','Add commitment'):''}</div>${j.promises.map(p=>`<div class="list-row"><div class="row-main"><h3>${e(p.ticket_customer_promise_summary)}</h3><p class="hint">Due ${e(fmt(p.ticket_customer_promise_due_at))}</p>${state.boot.user.write&&!j.terminal?button('promise','Record outcome',`data-id="${n(p.ticket_customer_promise_id)}"`):''}</div></div>`).join('')||'<p class="hint">No outstanding commitments.</p>'}</section>`;
  }
  async function route(view,id) {
    if(view==='jobs') {
      searchResult=await api('jobs',null,search);
      return header('Find work','Search scheduled, unscheduled, and previous jobs across clients you can access.',state.boot.user.write?button('create','New job','',false):'')+`<form id="workspace-job-search" class="form-grid inline-form"><label>Ticket or client<input type="search" name="q" value="${e(search.q)}" placeholder="Ticket number, subject, or client" maxlength="200"></label><div class="form-columns"><label>Assignment<select name="scope">${options({mine:'My work',all:'All accessible work'},search.scope)}</select></label><label>Include<select name="state">${options({open:'Open jobs',all:'Open and completed'},search.state)}</select></label></div><button>Search jobs</button></form><div id="job-results" class="list">${searchResult.jobs.map(jobRow).join('')||'<p class="hint">No jobs match these filters.</p>'}</div>${searchResult.next?button('jobs-more','Load more jobs'):''}`;
    }
    if(view==='new') {
      newClient=id?await api('client_context',null,{client_id:id}):null;
      const o=state.boot.options||{};
      return header('New field job',newClient?newClient.client_name:'Choose the client for this work.')+(!newClient?`<form id="workspace-client-search" class="search"><input name="q" aria-label="Client name" placeholder="Search clients" maxlength="200"><button>Find client</button></form><div id="client-results"></div>`:`<a class="back" href="#new">Choose another client</a><form id="workspace-create-form" class="form-grid inline-form"><input type="hidden" name="client_id" value="${n(id)}"><input type="hidden" name="followup_ticket_id" value="${n(state.followupTicket)}">${input('Subject','subject',state.followupSubject||'','required maxlength="500"')}${text('Work to do','details','','required maxlength="20000"')}<label>Job template · optional<select name="template_id">${choices(o.templates,'ticket_template_id','ticket_template_name',0,'No template')}</select></label><label>Work type<select name="work_type">${options(o.work_types,'incident')}</select></label><div class="form-columns"><label>Impact<select name="impact">${options(o.impacts,'medium')}</select></label><label>Urgency<select name="urgency">${options(o.urgencies,'medium')}</select></label></div><label>Site<select name="location_id">${choices(newClient.locations,'location_id','location_name',0)}</select></label><label>Contact<select name="contact_id">${choices(newClient.contacts,'contact_id','contact_name',0)}</select></label><label>Project<select name="project_id">${choices(newClient.projects,'project_id','project_name',0,'No project')}</select></label>${input('Scheduled start · optional','scheduled_at','','type="datetime-local"')}<p class="hint">This job will be assigned to you. Required documentation and approval rules still apply before completion.</p><button>Create job</button></form>`);
    }
    return null;
  }
  function planForm(j) {
    const o=state.boot.options||{};
    sheet('Manage this job',`<form id="workspace-plan-form" class="form-grid"><input type="hidden" name="expected_status" value="${n(j.status_id)}"><input type="hidden" name="expected_revision" value="${e(j.plan_version)}"><label>Status<select name="status_id">${choices(o.statuses,'ticket_status_id','ticket_status_name',j.status_id,'Choose status')}</select></label><label>Assigned technician<select name="assigned_to">${choices(j.owners,'user_id','user_name',j.assigned_to,'Unassigned')}</select></label><div id="handoff-fields" hidden>${text('Why hand off this job?','handoff_reason','','maxlength="500"')}${text('Current state for the next technician','handoff_state','','maxlength="500"')}</div><label>Work type<select name="work_type">${options(o.work_types,j.work_type)}</select></label><label>Impact<select name="impact">${options(o.impacts,j.impact)}</select></label><label>Urgency<select name="urgency">${options(o.urgencies,j.urgency)}</select></label><label>Waiting on<select name="waiting_on">${options(o.waiting,j.waiting_on)}</select></label>${text('Next action','next_action',j.next_action,'maxlength="500"')}${input('Next action due','next_action_due_at',local(j.next_action_due_at),'type="datetime-local"')}${input('Scheduled start','scheduled_at',local(j.scheduled_at),'type="datetime-local"')}<label>Site<select name="location_id">${choices(j.locations,'location_id','location_name',j.location_id)}</select></label><label>Contact<select name="contact_id">${choices(j.contacts,'contact_id','contact_name',j.contact_id)}</select></label><p class="hint">Waiting statuses require a next action and future due time. Reassignment requires a handoff when another technician already owns the job.</p><button>Save job details</button></form>`);
  }
  function transitionForm(j,kind) {
    const o=state.boot.options||{}, title={resolve:'Resolve ticket',close:'Close ticket',reopen:'Reopen ticket'}[kind];
    sheet(title,`<form id="workspace-transition-form" class="form-grid"><input type="hidden" name="transition" value="${kind}"><input type="hidden" name="expected_status" value="${n(j.status_id)}"><p><strong>${e(j.reference)} · ${e(j.subject)}</strong></p>${kind==='reopen'?'<p>The ticket returns to active work. Its previous resolution remains in the audit history.</p>':`${!j.terminal?`<label>Resolution code<select name="resolution_code" required>${options(o.resolution_codes,'',true)}</select></label>${text('Resolution summary','resolution_summary','','required minlength="10" maxlength="10000"')}${j.work_type==='problem'?text('Root cause','root_cause','','required minlength="10" maxlength="10000"'):''}`:`<p class="prose">${e(j.resolution_summary)}</p>`}${kind==='close'?`<label>Closure outcome<select name="closure_code" required>${options(o.closure_codes,'',true)}</select></label>`:''}<p class="hint">Finish the visit, review time, complete tasks, obtain approvals, and record commitment outcomes first. Completion checks run when you save.</p>${j.completion_error?`<p class="error-text">${e(j.completion_error)}</p>`:''}`}<button>${title}</button></form>`);
  }
  function replyForm(j,time=false) {
    const emails=(j.recipients||[]).map(r=>r.name?`${r.name} <${r.email}>`:r.email).join(', ');
    sheet(time?'Manual time entry':'Write a ticket update',`<form id="workspace-reply-form" class="form-grid">${time?`<input type="hidden" name="visibility" value="internal">${input('Minutes worked','minutes','','type="number" min="1" max="1440" required')}${input('When the work occurred','worked_at',local(new Date()),'type="datetime-local" required')}`:`<label>Visibility<select name="visibility">${options({internal:'Internal · technicians only',portal:'Customer portal',...(state.boot.options?.email_enabled?{email:'Customer portal and email'}:{})},'internal')}</select></label><input type="hidden" name="recipients_hash" value="${e(j.recipients_hash)}"><p id="reply-audience" class="hint">Only your team will see this note.</p><p id="reply-recipients" class="hint" hidden>Email recipients: ${e(emails||'No valid contact or watchers. Set a contact in Manage job.')}</p>`}${text(time?'Work performed':'Message','message','','required maxlength="20000"')}<p class="hint">${time?'Use this for work that was not recorded by a visit timer. Running visits must be finished first.':'Use Guided notes for a structured internal work record.'}</p><button>${time?'Save time entry':'Save update'}</button></form>`);
  }
  function showAsset(a,j) {
    asset=a;
    sheet(a.asset_name,`<div id="asset-detail"><dl class="facts">${[['Type',a.asset_type],['Make / model',[a.asset_make,a.asset_model].filter(Boolean).join(' ')],['Serial',a.asset_serial],['Operating system',a.asset_os],['Status',a.asset_status],['Physical location',a.asset_physical_location],['Warranty expires',a.asset_warranty_expire]].map(([key,value])=>`<dt>${key}</dt><dd>${e(value||'Not recorded')}</dd>`).join('')}</dl><p class="prose">${e(a.asset_notes)}</p><h3>Network interfaces</h3>${(a.interfaces||[]).map(i=>`<div class="list-row"><div><strong>${e(i.interface_name)}</strong><p>${e([i.interface_ip,i.interface_ipv6,i.interface_mac].filter(Boolean).join(' · '))}</p></div></div>`).join('')||'<p class="hint">No interfaces recorded.</p>'}${state.boot.user.client_write&&!j.terminal?`<div class="actions">${button('asset-edit','Record asset update')}${n(j.asset_id)!==n(a.asset_id)?button('asset-link','Use as ticket asset'):''}</div>`:''}</div>`);
  }
  async function click(action,b) {
    if(!action.startsWith('workspace-'))return false;
    const a=action.slice(10), j=state.job;
    if(a==='create'){state.followupTicket=0;state.followupSubject='';location.hash='#new';}
    else if(a==='followup'){state.followupTicket=j.ticket_id;state.followupSubject='Follow-up: '+j.subject;location.hash='#new/'+j.client_id;}
    else if(a==='plan')planForm(j);
    else if(a==='approval')approvalForm(j,b);
    else if(a==='transition')transitionForm(j,b.dataset.kind);
    else if(a==='reply'||a==='time')replyForm(j,a==='time');
    else if(a==='jobs-more') {b.disabled=true;try{const result=await api('jobs',null,{...search,before:searchResult.next});$('#job-results').insertAdjacentHTML('beforeend',result.jobs.map(jobRow).join(''));searchResult.next=result.next;if(!result.next)b.remove();}finally{b.disabled=false;}}
    else if(a==='history-more'){b.disabled=true;try{const h=await api('history',null,{ticket_id:j.ticket_id,before:historyNext});$('#history-list').insertAdjacentHTML('beforeend',historyRows(h.entries));historyNext=h.next;if(!h.next)b.remove();}finally{b.disabled=false;}}
    else if(a==='asset')showAsset(await api('asset',null,{ticket_id:j.ticket_id,asset_id:b.dataset.id}),j);
    else if(a==='asset-link')sheet('Link ticket asset',`<form id="workspace-asset-link-form" class="form-grid"><input type="hidden" name="asset_id" value="${n(asset.asset_id)}"><input type="hidden" name="operation" value="link"><p>Use ${e(asset.asset_name)} as the primary asset for ${e(j.reference)}?</p><p class="hint">The ticket’s service coverage will be evaluated for this asset.</p><button>Link asset</button></form>`);
    else if(a==='asset-edit')sheet('Record asset update',`<form id="workspace-asset-form" class="form-grid"><input type="hidden" name="asset_id" value="${n(asset.asset_id)}">${input('Status','status',asset.asset_status,'maxlength="200"')}${input('Physical location','physical_location',asset.asset_physical_location,'maxlength="200"')}${text('What changed?','note','','required maxlength="10000"')}<p class="hint">Adds a dated update to the existing asset notes.</p><button>Save asset update</button></form>`);
    else if(a==='credential') {
      const version=++secretVersion;
      const secret=await api('credential_reveal',{ticket_id:j.ticket_id,credential_id:n(b.dataset.id)});
      if(version!==secretVersion||document.visibilityState!=='visible'||state.cover)return true;
      const url=/^https?:\/\//i.test(secret.uri||'')?secret.uri:'';
      sheet(secret.name,`<div id="credential-secret" class="form-grid"><p class="hint">Clears automatically in 30 seconds.</p>${input('Username','credential_username',secret.username,'readonly autocomplete="off"')}${input('Password','credential_password',secret.password,'readonly autocomplete="off"')}${secret.otp?input('One-time code','credential_otp',secret.otp,'readonly autocomplete="off"'):''}<div class="actions">${button('copy-secret','Copy username','data-field="credential_username"')}${button('copy-secret','Copy password','data-field="credential_password"')}</div>${url?`<a href="${e(url)}" target="_blank" rel="noopener noreferrer">Open sign-in page</a>`:''}<p class="prose">${e(secret.note)}</p></div>`);
      secretTimer=setTimeout(clearSecrets,secret.otp_expires_at?Math.min(30000,Math.max(0,secret.otp_expires_at-Date.now())):30000);
    }
    else if(a==='copy-secret'){const value=$(`[name="${b.dataset.field}"]`,$('#credential-secret'))?.value;if(value){await navigator.clipboard.writeText(value);notice('Copied.');}}
    else if(a==='promise') {const id=n(b.dataset.id);sheet(id?'Record commitment outcome':'Customer commitment',`<form id="workspace-promise-form" class="form-grid"><input type="hidden" name="promise_id" value="${id}">${id?`<label>Outcome<select name="status">${options({fulfilled:'Fulfilled',cancelled:'Cancelled'},'fulfilled')}</select></label>${text('Outcome and reason','reason','','required maxlength="500"')}`:`${text('What did we commit to?','summary','','required maxlength="500"')}${input('Due','due_at','','type="datetime-local" required')}`}<button>Save commitment</button></form>`);}
    else if(a==='task-new'||a==='task-reopen') {sheet(a==='task-new'?'Add a task':'Reopen task',`<form id="workspace-task-form" class="form-grid"><input type="hidden" name="operation" value="${a==='task-new'?'create':'reopen'}"><input type="hidden" name="task_id" value="${n(b.dataset.id)}"><input type="hidden" name="ticket_id" value="${n(b.dataset.ticket||j.ticket_id)}">${a==='task-new'?input('Task name','name','','required maxlength="255"')+text('Instructions','instructions','','maxlength="10000"'):text('Why does this task need more work?','reason','','required maxlength="255"')}<button>Save task</button></form>`);}
    else if(a==='doc-assess')sheet('Documentation impact',`<form id="workspace-doc-action-form" class="form-grid"><input type="hidden" name="operation" value="assess"><label class="check"><input type="checkbox" name="configuration_change" value="1" ${n(j.configuration_change)?'checked':''}>This work changes the client configuration.</label><label>Documentation affected<select name="impact" required>${options({None:'No required documentation affected',Required:'Required documentation affected'},j.documentation_impact,true)}</select></label><p class="hint">Configuration changes require affected documentation to be linked and verified.</p><button>Save assessment</button></form>`);
    else if(a==='doc-verify'){const r=j.requirements.find(r=>n(r.id)===n(b.dataset.id));sheet('Verify documentation',`<form id="workspace-doc-action-form" class="form-grid"><input type="hidden" name="operation" value="verify"><input type="hidden" name="obligation_id" value="${n(r.id)}"><input type="hidden" name="revision" value="${n(r.revision)}"><p><strong>${e(r.name)}</strong></p><label>Reviewed document<select name="document_id" required>${choices(j.documents,'document_id','document_name',r.document_id,'Choose document')}</select></label><label>Evidence<select name="evidence_type">${options({document:'Reviewed document',note:'Verification note',url:'Evidence URL',file:'Client file',none:'No evidence required by policy'},r.evidence_policy==='reference'?'document':r.evidence_policy)}</select></label><label>Client file · for file evidence<select name="file_id">${choices(j.client_files,'file_id','file_name',0,'Choose file')}</select></label>${text('Verification note or evidence URL','note','','maxlength="4000"')}<p class="hint">Required evidence: ${e(r.evidence_policy)}. The saved requirement policy will be checked.</p><label class="check"><input type="checkbox" name="confirm_verified" value="1" required>I reviewed this document and verified it against the client environment.</label><button>Verify documentation</button></form>`);}
    else if(a==='camera')sheet('Take a photo',`<form id="photo-form" class="form-grid"><label>Photo<input name="photo" type="file" accept="image/jpeg,image/png,image/webp" capture="environment" required></label>${input('Caption','caption','','required maxlength="200"')}<label>Evidence for<select name="task_id">${taskOptions(j)}</select></label><button>Upload photo</button></form>`);
    else if(a==='document-full'){activeDocument=n(b.dataset.id);sheet('Full document',`<iframe class="file-preview" title="Client document" sandbox="allow-same-origin" src="/agent/field/api.php?action=document_view&ticket_id=${j.ticket_id}&document_id=${activeDocument}&theme=${document.documentElement.dataset.theme==='dark'?'dark':'light'}"></iframe>`);}
    else if(a==='document-update'){activeDocument=n(b.dataset.id);sheet(activeDocument?'Add a documentation update':'Create client documentation',`<form id="workspace-document-form" class="form-grid"><input type="hidden" name="document_id" value="${activeDocument}">${!activeDocument?input('Document name','name','','required maxlength="200"'):''}${text('Documentation','note','','required maxlength="20000"')}<p class="hint">${activeDocument?'Adds a dated section and preserves existing diagrams and content. Linked verification becomes due for review.':'Saves to this client’s documentation.'}</p><button>Save documentation</button></form>`);}
    else if(a==='file'){const name=b.dataset.name||'Ticket attachment';const url=`/agent/field/api.php?action=attachment&ticket_id=${j.ticket_id}&attachment_id=${n(b.dataset.id)}`;sheet(name,`<p><a class="button secondary" href="${url}" target="_blank" rel="noopener noreferrer">Open or download file</a></p>${/\.(png|jpe?g|webp)$/i.test(name)?`<img class="attachment-preview" src="${url}" alt="${e(name)}">`:/\.pdf$/i.test(name)?`<iframe class="file-preview" title="${e(name)}" sandbox src="${url}"></iframe>`:'<p class="hint">Use Open or download file to view this attachment on your device.</p>'}`);}
    else if(a==='files-more'){const result=await api('files',null,{ticket_id:j.ticket_id,before:fileNext});$('#file-list').insertAdjacentHTML('beforeend',fileRows(result.files));fileNext=result.next;if(!fileNext)b.remove();}
    return true;
  }
  function fileRows(files) {return files.map(f=>`<div class="list-row"><div class="row-main">${button('file',f.ticket_attachment_name,`data-id="${n(f.ticket_attachment_id)}" data-name="${e(f.ticket_attachment_name)}"`)}<p class="muted">${e(fmt(f.ticket_attachment_created_at))}</p></div></div>`).join('');}
  async function files(j,task=0) {
    const result=await api('files',null,{ticket_id:j.ticket_id});fileNext=result.next;
    return `${state.boot.user.write&&!j.terminal?`<form id="workspace-file-form" data-ticket-id="${n(j.ticket_id)}" class="form-grid inline-form"><div class="section-head"><h2>Files and evidence</h2>${button('camera','Take a photo')}</div><label>Choose a file<input name="file" type="file" required accept="application/pdf,text/plain,image/jpeg,image/png,image/webp"></label>${input('Description','caption','','required maxlength="200"')}<label>Attach evidence to<select name="task_id">${taskOptions(j,task)}</select></label><button>Upload file</button><p class="hint">PDF, text, JPG, PNG, or WebP · Up to 12 MB · Uploads require a connection.</p></form>`:''}<h2 class="subsection">All ticket attachments</h2><div id="file-list" class="list">${fileRows(result.files)||'<p class="hint">No attachments yet.</p>'}</div>${fileNext?button('files-more','Load more files'):''}`;
  }
  async function submit(form) {
    if(!form.id.startsWith('workspace-'))return false;
    let data=Object.fromEntries(new FormData(form)), action;
    if(form.id==='workspace-job-search'){search={...search,...data};location.hash='#jobs';await ctx.route();return true;}
    if(form.id==='workspace-client-search'){const clients=await api('clients',null,data);$('#client-results').innerHTML=clients.length?`<div class="list">${clients.map(c=>`<a class="list-row title" href="#new/${n(c.client_id)}">${e(c.client_name)}</a>`).join('')}</div>`:empty('No matching clients','Search for another client name.');return true;}
    action=({'workspace-approval-form':'approval','workspace-create-form':'create_job','workspace-plan-form':'plan','workspace-transition-form':'transition','workspace-reply-form':'reply','workspace-promise-form':'promise','workspace-task-form':'task_update','workspace-asset-form':'asset_update','workspace-asset-link-form':'asset_update','workspace-document-form':'document_update','workspace-file-form':'file','workspace-doc-action-form':'documentation_action'})[form.id];
    if(!action)return true;
    if(action==='approval')data.kind ||= n(data.task_id)?'task':'ticket';
    if(action==='create_job')data.ticket_id=0;else data.ticket_id ||= form.dataset.ticketId||state.job?.ticket_id;
    // Pass an explicit offset; server translates device time to the PSA timezone.
    for(const name of ['worked_at','scheduled_at','next_action_due_at','due_at'])if(data[name])data[name]=new Date(data[name]).toISOString();
    if(action==='file'){data=new FormData(form);data.set('ticket_id',form.dataset.ticketId);}
    const result=await write(action,data,form);if(!result)return true;
    closeSheet();
    if(action==='create_job'){state.followupTicket=0;state.followupSubject='';await ctx.boot();location.hash=jobHref(result.ticket_id);}
    else await reload();
    return true;
  }
  document.addEventListener('change',ev=>{
    if(ev.target.id==='job-section'){state.sectionFocus=jobHref(state.job.ticket_id,ev.target.value);location.hash=state.sectionFocus;}
    if(ev.target.matches('#workspace-approval-form [name=route]')){$('#approval-user').hidden=ev.target.value!=='internal:specific';$('#approval-contact').hidden=ev.target.value!=='client:specific';}
    if(ev.target.matches('#workspace-reply-form [name=visibility]')){const value=ev.target.value;$('#reply-audience').textContent=value==='internal'?'Only your team will see this note.':'The customer will see this update on the ticket.';$('#reply-recipients').hidden=value!=='email';$('#workspace-reply-form button').textContent=value==='email'?'Send customer update':'Save update';}
    if(ev.target.matches('#workspace-plan-form [name=assigned_to]')){const handoff=n(ev.target.value)!==n(state.job.assigned_to)&&n(state.job.assigned_to)>0;$('#handoff-fields').hidden=!handoff;$('#handoff-fields').querySelectorAll('textarea').forEach(el=>el.required=handoff);}
  });
  document.addEventListener('input',ev=>{if(ev.target.id==='credential-search'){$('#credential-list').querySelectorAll('[data-credential-name]').forEach(row=>row.hidden=!row.dataset.credentialName.includes(ev.target.value.toLowerCase()));}});
  document.addEventListener('visibilitychange',()=>{if(document.visibilityState!=='visible')clearSecrets();});
  function documentation(j) {
    return `<section class="subsection"><div class="section-head"><h2>Documentation for this job</h2>${state.boot.user.write&&!j.terminal?button('doc-assess','Assess impact'):''}</div><p class="hint">${e(j.documentation_impact||'Not assessed')}${n(j.configuration_change)?' · Configuration change':''}</p>${(j.requirements||[]).map(r=>`<div class="list-row"><div class="row-main"><h3>${e(r.name)}</h3><p class="hint">${e(r.status)}${n(r.linked)?' · Linked to this job':''}</p></div>${state.boot.user.write&&!j.terminal?button('doc-verify','Review / verify',`data-id="${n(r.id)}"`):''}</div>`).join('')}</section>`;
  }
  return {route,click,submit,clearSecrets,communication,resources,jobActions,promises,assetRows,files,button,documentation,approvals};
}
