ServerTokens Prod
ServerSignature Off
TraceEnable Off
ServerName psa.n45tech.com

<VirtualHost *:80>
    ServerName psa.n45tech.com
    DocumentRoot /var/www/html

    SetEnvIf X-Forwarded-Proto "^https$" HTTPS=on
    RemoteIPHeader X-Forwarded-For
    RemoteIPTrustedProxy 127.0.0.1
    RemoteIPTrustedProxy 172.16.0.0/12

    <Directory /var/www/html>
        AllowOverride All
        Options -Indexes
        Require all granted
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
