// Synthetic browser fixtures only; no live PSA credentials or customer data.
const {chromium}=require('playwright');
const http=require('node:http');const fs=require('node:fs');const path=require('node:path');const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../..');
const screenshots=process.env.N45_FIELD_SCREENSHOTS||path.join(root,'.impeccable/review');
fs.mkdirSync(screenshots,{recursive:true});
const now=new Date().toISOString();
const job={ticket_id:101,reference:'N45-1042',subject:'Replace the branch firewall',client_id:12,client_name:'Example Client',location_id:3,location_name:'North branch',address:'10 Example Way, Test City',scheduled_at:now,priority:'High',work_type:'project',status:'In Progress',project_id:9,project_name:'Branch network refresh',assigned_name:'Alex Morgan',assigned_to:7,terminal:false,pin_valid:true,pin_latitude:45.5,pin_longitude:-73.5,pin_radius_meters:150,address_hash:'testhash',details:'Replace the firewall and verify connectivity before handing the site back to the branch manager.',next_action:'Confirm the backup, then connect the replacement appliance.',site_notes:'Call the branch manager at the front entrance. The network cabinet is in the staff room.',site_hours:'Monday–Friday, 8 am–5 pm',contact:{name:'Jordan Lee',phone:'5550100100',email:'jordan@example.invalid'},promises:[],tasks:[{task_id:21,task_name:'Verify the configuration backup',task_instructions:'Check the backup timestamp and confirm the restore procedure.',task_state:'Ready',task_assigned_to:7,assigned_name:'Alex Morgan',task_due_at:null,task_waiting_reason:null,task_evidence_required:'note',task_evidence_prompt:'Record the backup timestamp and validation result.',task_completed_at:null,can_complete:false,completion_error:'Required note evidence must be added first.',dependencies:[]}],documents:[{document_id:4,document_name:'North branch network and site access',document_description:'Access instructions, network diagram, and escalation contacts',last_verified_at:now,asset_linked:1}],assets:[{asset_id:2,asset_name:'Branch firewall',asset_type:'Firewall',asset_make:'Example',asset_model:'FW-40',asset_serial:'EX-1042'}],owners:[{user_id:7,user_name:'Alex Morgan'}],blockers:[],notes:[],attachments:[]};
const data={user:{id:7,name:'Alex Morgan',write:true,admin:true,verify_site:true,documents:true},csrf_token:'fixture-csrf',theme:'light',jobs:[job],projects:[{project_id:9,project_name:job.project_name,client_name:job.client_name,manager_name:'Alex Morgan',project_due:'2026-09-18',ticket_count:3,completed_count:1}],visits:[],issues:[],server_time:now};
Object.assign(job,{status_id:2,closed:false,contact_id:1,impact:'medium',urgency:'medium',plan_version:'fixture-version',waiting_on:'none',recipients:[{name:'Jordan Lee',email:'jordan@example.invalid'}],recipients_hash:'fixture-recipients',history:{entries:[{ticket_reply_id:60,ticket_reply:'Customer reported an intermittent connection.',ticket_reply_type:'Client',ticket_reply_created_at:now,author:'Jordan Lee'}],next:20},contacts:[{contact_id:1,contact_name:'Jordan Lee',contact_email:'jordan@example.invalid',contact_mobile:'5550100100',contact_title:'Branch manager'}],locations:[{location_id:3,location_name:'North branch'}],networks:[{network_name:'Staff network',network:'192.0.2.0/24',network_gateway:'192.0.2.1',network_primary_dns:'192.0.2.1'}],credentials:[{credential_id:5,credential_name:'Branch firewall admin',credential_description:'Local admin access'}],documentation_impact:'None',requirements:[],client_files:[],approvals:[{id:3,kind:'ticket',task_id:0,task_name:'Entire ticket',route_label:'Taylor Jones',status:'pending',scope:'internal',type:'specific',created_by:7,can_decide:false,actionable:true,required_user_id:8}]});
Object.assign(data.user,{client_write:true,credentials:true});
data.options={templates:[{ticket_template_id:9,ticket_template_name:'Firewall replacement'}],email_enabled:true,statuses:[{ticket_status_id:2,ticket_status_name:'In Progress'},{ticket_status_id:3,ticket_status_name:'Waiting on Client'}],work_types:{incident:'Incident',problem:'Problem investigation'},impacts:{low:'One person',medium:'Several people',high:'Critical service'},urgencies:{low:'Can be planned',medium:'Normal operations',high:'Work stopped'},waiting:{none:'No external blocker',client:'Client'},resolution_codes:{fixed:'Fixed'},closure_codes:{client_confirmed:'Client confirmed completion'}};
let fileLabel='Firewall-label.png';const writes=[];let dropNextNote=false;let matchCalls=0;let noMatches=false;
const server=http.createServer(async(req,res)=>{
  const url=new URL(req.url,'http://localhost');
  if(url.pathname==='/agent/field/api.php'){
    res.setHeader('content-type','application/json');res.setHeader('cache-control','no-store');
    let input=null;if(req.method==='POST'){const chunks=[];for await(const chunk of req)chunks.push(chunk);const body=Buffer.concat(chunks);if((req.headers['content-type']||'').includes('application/json'))input=JSON.parse(body);else input=Object.fromEntries(await new Request('http://localhost/fixture',{method:'POST',headers:req.headers,body}).formData());}
    const action=input?.action||url.searchParams.get('action');let result;
    if(action==='boot')result=data;
    else if(action==='ticket')result=url.searchParams.get('ticket_id')==='102'?{...job,ticket_id:102,reference:'N45-1043',subject:'Validate the guest network'}:job;
    else if(action==='match'){matchCalls++;result={candidates:noMatches?[]:[{ticket_id:101,location_id:3,distance_meters:5}]};}
    else if(action==='project')result={...data.projects[0],project_description:'Upgrade the branch network with validated handover.',jobs:[job,{...job,ticket_id:102,reference:'N45-1043',subject:'Validate the guest network',assigned_to:8,tasks:[{...job.tasks[0],task_id:22,task_assigned_to:8,assigned_name:'Taylor Jones',task_name:'Test guest isolation'}]}],blockers:job.blockers};
    else if(action==='document')result={id:4,name:job.documents[0].document_name,content:'Site access\nCall the branch manager.\n<script>alert("xss")</script>'};
    else if(action==='documents')result=job.documents;
    else if(action==='jobs')result={jobs:[job],next:null};
    else if(action==='clients')result=[{client_id:12,client_name:job.client_name}];
    else if(action==='client_context')result={client_id:12,client_name:job.client_name,contacts:job.contacts,locations:job.locations,projects:[],owners:job.owners};
    else if(action==='history')result={entries:[{ticket_reply_id:19,ticket_reply:'Earlier fixture history',ticket_reply_type:'Internal',ticket_reply_created_at:now,author:'Alex Morgan'}],next:null};
    else if(action==='files')result={files:[{ticket_attachment_id:8,ticket_attachment_name:fileLabel,ticket_attachment_created_at:now}],next:null};
    else if(action==='asset')result={...job.assets[0],asset_notes:'Installed in the staff network cabinet',asset_status:'Active',interfaces:[{interface_name:'LAN',interface_ip:'192.0.2.1',interface_mac:'00:11:22:33:44:55'}]};
    else if(action==='credential_reveal'){assert.equal(input.csrf_token,'fixture-csrf');assert.equal(input.request_key,undefined,'Secrets must not create receipt records');result={name:'Branch firewall admin',username:'fixture-admin',password:'fixture-secret-value',note:'Fixture only'};}

    else if(action==='assets')result=job.assets;
    else if(input){writes.push(input);assert.equal(input.csrf_token,'fixture-csrf');assert.match(input.request_key,/^[0-9a-f-]{36}$/);
      if(action==='visit'){
        assert.equal(Number(input.confirm_onsite),1);data.visits=[{visit_id:1,visit_ticket_id:101,visit_client_id:12,visit_location_id:3,visit_user_id:7,visit_active_user_id:7,visit_status:'onsite',visit_started_at:now,visit_arrived_at:now,visit_finished_at:null,visit_share_location:0,client_name:job.client_name,ticket_prefix:'N45-',ticket_number:1042,ticket_subject:job.subject,segments:[{segment_id:1,segment_ticket_id:101,segment_active_visit_id:1,segment_kind:'onsite',segment_started_at:now,segment_ended_at:null,segment_submitted_at:null,ticket_subject:job.subject}]}];result={message:'Onsite recorded.',visit_id:1};
      }else if(action==='approval'){assert.equal(input.kind,'ticket');assert.equal(input.operation,'retry');assert.equal(input.approval_id,'3');assert.ok(input.reason);result={message:'Approval requested.'};
      }else if(action==='plan'){assert.equal(input.expected_revision,'fixture-version');assert.equal(input.assigned_to,'7');result={message:'Job details saved.'};
      }else if(action==='create_job'){assert.equal(input.client_id,'12');assert.equal(input.ticket_id,0);assert.equal(input.template_id,'9');result={message:'Job created.',ticket_id:102};
      }else if(action==='reply'){assert.ok(['internal','portal','email'].includes(input.visibility));if(input.visibility==='email')assert.equal(input.recipients_hash,'fixture-recipients');result={message:'Update saved.'};
      }else if(action==='transition'){assert.ok(input.resolution_summary.length>10);result={message:'Ticket resolved.'};
      }else if(action==='note'){
        assert.ok(input.work_action&&input.work_result&&input.work_next_step);assert.equal(input.task_id,0);
        job.notes=[{ticket_reply_id:1,ticket_reply:input.work_action,ticket_reply_type:'Internal',ticket_reply_created_at:now,user_name:'Alex Morgan'}];result={message:'Work note saved.',reply_id:1};
        if(dropNextNote){dropNextNote=false;res.statusCode=500;res.end(JSON.stringify({error:'The commit response was lost. Retry this form.'}));return;}
      }else if(action==='issue_update'){assert.ok(input.note,'Issue response must reach the server note field');result={message:'Issue resolved.'};}
      else result={message:'Saved.'};
    }
    else {res.statusCode=404;res.end(JSON.stringify({error:'Missing fixture'}));return;}
    res.end(JSON.stringify({data:result}));return;
  }
  const target=url.pathname==='/agent/field/'?'/agent/field/shell.html':url.pathname;
  const file=path.join(root,target);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.statusCode=404;res.end();return;}
  const types={'.html':'text/html','.mjs':'text/javascript','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.webmanifest':'application/manifest+json'};
  res.setHeader('content-type',types[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));
});
(async()=>{
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${server.address().port}`;
 const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
 try {
  const context=await browser.newContext({viewport:{width:393,height:852},isMobile:true,hasTouch:true,userAgent:'Mozilla/5.0 (Linux; Android 14; Pixel 8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Mobile Safari/537.36',geolocation:{latitude:45.5,longitude:-73.5,accuracy:12},permissions:['geolocation']});
  const page=await context.newPage();const errors=[];page.on('pageerror',err=>errors.push(err.message));
  await page.goto(base+'/agent/field/');await page.waitForURL('**/#job/101/overview');await page.getByRole('heading',{name:'At the right stop?'}).waitFor();
  assert.equal(writes.length,0,'Opening a matched job must not mark onsite');
  await page.screenshot({path:path.join(screenshots,'mobile.png'),fullPage:true});
  const desktop=await context.newPage();await desktop.setViewportSize({width:1440,height:1000});await desktop.goto(base+'/agent/field/#project/9');await desktop.getByRole('button',{name:'Entire project'}).click();await desktop.screenshot({path:path.join(screenshots,'desktop.png'),fullPage:true});await page.bringToFront();
  await page.getByRole('button',{name:'Mark onsite',exact:true}).click();assert.equal(writes.length,0,'Opening arrival confirmation must not write');
  await page.getByRole('button',{name:'Confirm onsite',exact:true}).click();await page.getByRole('heading',{name:'Onsite',exact:true}).waitFor();assert.equal(writes.filter(w=>w.action==='visit').length,1);
  await page.getByLabel('Job section',{exact:true}).selectOption('notes');await page.getByRole('heading',{name:'Guided work note'}).waitFor();
  await page.locator('[name=work_action]').fill('Filled note before recovery');await page.locator('[name=work_result]').fill('A meaningful result');await page.locator('[name=work_next_step]').fill('A meaningful next step');
  const notesBeforeRecovery=writes.filter(w=>w.action==='note').length;
  await page.getByRole('button',{name:'Enable encrypted recovery'}).click();assert.equal(writes.filter(w=>w.action==='note').length,notesBeforeRecovery,'Recovery action submitted a note');await page.getByLabel('Recovery passphrase',{exact:true}).fill('fixture passphrase 45');await page.getByLabel('Confirm passphrase').fill('fixture passphrase 45');await page.getByRole('button',{name:'Enable recovery',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('#sheet').open);
  await page.locator('[name=work_action]').fill('Secret fixture note: verified backup');await page.locator('[name=work_result]').fill('Backup restored successfully');await page.locator('[name=work_next_step]').fill('Proceed with the firewall replacement');
  await page.waitForFunction(()=>document.querySelector('#note-save-state')?.textContent.includes('Encrypted draft saved'));
  const stored=await page.evaluate(()=>JSON.stringify(localStorage));assert.ok(!stored.includes('Secret fixture'),'Draft plaintext entered persistent storage');
  await page.reload();await page.getByRole('heading',{name:'Guided work note'}).waitFor();assert.equal(await page.locator('[name=work_action]').inputValue(),'','Reload exposed a locked draft');
  await page.getByRole('link',{name:'Drafts',exact:true}).click();await page.getByRole('button',{name:'Unlock note recovery'}).click();await page.getByLabel('Recovery passphrase').fill('wrong passphrase');await page.getByRole('button',{name:'Unlock notes',exact:true}).click();await page.getByText('The recovery passphrase did not unlock these notes.',{exact:true}).waitFor();
  await page.getByLabel('Recovery passphrase').fill('fixture passphrase 45');await page.getByRole('button',{name:'Unlock notes',exact:true}).click();await page.getByRole('button',{name:'Open draft',exact:true}).waitFor();
  await context.setOffline(true);await page.reload();await page.getByRole('button',{name:'Unlock note recovery'}).waitFor();await page.getByRole('button',{name:'Unlock note recovery'}).click();await page.getByLabel('Recovery passphrase').fill('fixture passphrase 45');await page.getByRole('button',{name:'Unlock notes',exact:true}).click();await page.getByRole('button',{name:'Open draft'}).click();await page.getByRole('heading',{name:'Guided work note'}).waitFor();assert.equal(await page.locator('[name=work_action]').inputValue(),'Secret fixture note: verified backup');
  await page.locator('[name=work_result]').fill('Offline recovery verified');await page.waitForFunction(()=>document.querySelector('#note-save-state')?.textContent.includes('Encrypted draft saved'));
  await context.setOffline(false);await page.reload();await page.getByRole('button',{name:'Unlock note recovery'}).click();await page.getByLabel('Recovery passphrase').fill('fixture passphrase 45');await page.getByRole('button',{name:'Unlock notes',exact:true}).click();await page.getByRole('button',{name:'Open draft'}).click();await page.getByRole('heading',{name:'Guided work note'}).waitFor();
  dropNextNote=true;await page.getByRole('button',{name:'Save work note',exact:true}).click();await page.locator('#note-form .error-text').waitFor();
  await page.getByRole('button',{name:'Save work note',exact:true}).click(); // Retry the exact payload after a lost response.
  await page.waitForFunction(()=>document.querySelector('#notice')?.textContent==='Work note saved.');
  const notes=writes.filter(w=>w.action==='note');assert.equal(notes.length,2);assert.deepEqual(notes[0],notes[1],'A dropped response changed the retry payload');
  await page.getByLabel('Job section',{exact:true}).selectOption('docs');await page.getByRole('button',{name:job.documents[0].document_name}).click();assert.equal(await page.locator('#doc-content script').count(),0,'Document content was executable');
  await page.getByRole('link',{name:'Projects',exact:true}).click();await page.getByRole('link',{name:job.project_name,exact:true}).click();await page.getByRole('button',{name:'Entire project'}).click();await page.getByText('Test guest isolation',{exact:true}).waitFor();await page.getByRole('button',{name:'My tasks',exact:true}).click();assert.equal(await page.getByText('Test guest isolation',{exact:true}).count(),0);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Mobile layout overflows');
  const cached=await page.evaluate(async()=>{const urls=[];for(const key of await caches.keys())for(const req of await(await caches.open(key)).keys())urls.push(req.url);return urls;});assert.ok(cached.length);assert.ok(cached.every(url=>!url.includes('api.php')&&!url.includes('/uploads/')&&!url.includes('/client/')),'Private data entered the service worker cache');
  await page.getByRole('button',{name:'Cover screen'}).click();await page.locator('#privacy').waitFor({state:'visible'});assert.equal(await page.locator('#work').evaluate(el=>el.inert),true);
  await page.getByRole('button',{name:'Reopen Field Mode'}).click();await page.getByRole('button',{name:'My tasks'}).waitFor();
  assert.equal(await desktop.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Desktop layout overflows');
  const second=await browser.newContext({viewport:{width:393,height:852},isMobile:true,hasTouch:true,userAgent:'Mozilla/5.0 (Linux; Android 14; Pixel 8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Mobile Safari/537.36',geolocation:{latitude:45.5,longitude:-73.5,accuracy:12},permissions:['geolocation']});
  const temp=await second.newPage();await temp.goto(base+'/agent/field/#job/101/notes');await temp.locator('[name=work_action]').fill('Keep this unsaved note in this tab');
  await temp.evaluate(()=>location.hash='#job/102/notes');await temp.getByRole('heading',{name:'Validate the guest network',exact:true}).waitFor();await temp.locator('[name=work_action]').fill('Separate second job note');
  await temp.evaluate(()=>location.hash='#job/101/notes');await temp.getByRole('heading',{name:'Replace the branch firewall',exact:true}).waitFor();assert.equal(await temp.locator('[name=work_action]').inputValue(),'Keep this unsaved note in this tab','Switching tickets lost a note without an unlocked vault');
  await temp.getByLabel('Job section',{exact:true}).selectOption('issues');await temp.getByRole('button',{name:'Report issue',exact:true}).click();await temp.locator('#issue-form [name=title]').fill('Keep this open issue form');
  await temp.evaluate(()=>{window.originalDateNow=Date.now;const later=Date.now()+61000;Date.now=()=>later;});await temp.locator('#privacy').waitFor({state:'visible'});assert.equal(await temp.locator('#sheet').evaluate(el=>el.open),false,'Privacy cover left the modal document inert');
  await temp.evaluate(()=>Date.now=window.originalDateNow);const beforeResume=matchCalls;await temp.getByRole('button',{name:'Reopen Field Mode'}).click();await temp.waitForFunction(()=>document.querySelector('#sheet').open);assert.equal(await temp.locator('#issue-form [name=title]').inputValue(),'Keep this open issue form','Privacy cover discarded the form');assert.ok(matchCalls>beforeResume,'Resume skipped foreground arrival matching');
  await temp.getByRole('button',{name:'Close',exact:true}).click();data.visits=[];
  await temp.evaluate(()=>location.hash='#job/101/overview');await temp.getByRole('heading',{name:'Replace the branch firewall',exact:true}).waitFor();
  await temp.getByRole('button',{name:'Cover screen'}).click();await temp.getByRole('button',{name:'Reopen Field Mode'}).click();await temp.getByRole('heading',{name:'At the right stop?',exact:true}).waitFor();
  await temp.evaluate(()=>{window.originalGetPosition=navigator.geolocation.getCurrentPosition.bind(navigator.geolocation);navigator.geolocation.getCurrentPosition=(success,error)=>error({code:1});});
  await temp.getByRole('button',{name:'Cover screen'}).click();await temp.getByRole('button',{name:'Reopen Field Mode'}).click();await temp.getByRole('heading',{name:'Start this visit',exact:true}).waitFor();assert.equal(await temp.getByRole('heading',{name:'At the right stop?',exact:true}).count(),0,'Denied location retained a stale arrival match');
  await temp.evaluate(()=>navigator.geolocation.getCurrentPosition=window.originalGetPosition);noMatches=true;
  await temp.getByRole('button',{name:'Cover screen'}).click();await temp.getByRole('button',{name:'Reopen Field Mode'}).click();await temp.waitForFunction(()=>document.querySelector('#notice').textContent.startsWith('No verified scheduled stop'));assert.equal(await temp.getByRole('heading',{name:'At the right stop?',exact:true}).count(),0,'An empty match result retained the old job cue');
  await second.close();
  const mobile=await browser.newContext({viewport:{width:393,height:852},isMobile:true,hasTouch:true,userAgent:'Mozilla/5.0 (Linux; Android 14; Pixel 8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Mobile Safari/537.36'});const work=await mobile.newPage();work.on('pageerror',err=>errors.push(err.message));
  await work.goto(base+'/agent/field/#job/101/overview');await work.getByRole('button',{name:'Manage job',exact:true}).click();await work.getByLabel('Next action',{exact:true}).fill('Confirm testing with the manager');await work.getByRole('button',{name:'Save job details'}).click();await work.waitForFunction(()=>!document.querySelector('#sheet').open);
  await work.getByLabel('Job section',{exact:true}).selectOption('approvals');await work.getByRole('heading',{name:'Approvals',exact:true}).waitFor();assert.equal(await work.getByRole('button',{name:'Record decision'}).count(),0,'Requester can see self-approval');await work.getByRole('button',{name:'Request again'}).click();await work.getByLabel('Reason',{exact:true}).fill('Requested evidence is now available');await work.getByRole('button',{name:'Send approval request'}).click();await work.waitForFunction(()=>!document.querySelector('#sheet').open);
  await work.getByLabel('Job section',{exact:true}).selectOption('conversation');await work.getByText('Customer reported an intermittent connection.').waitFor();assert.equal(await work.evaluate(()=>document.activeElement.id),'job-section','Section selection lost keyboard focus');assert.equal(await work.locator('#section-announcement').textContent(),'Conversation section loaded.');await work.getByRole('button',{name:'Load earlier entries'}).click();await work.getByText('Earlier fixture history').waitFor();
  await work.getByRole('button',{name:'Write an update'}).click();assert.equal(await work.getByLabel('Visibility').inputValue(),'internal','Updates must default to internal');await work.getByLabel('Visibility').selectOption('email');await work.getByText('Email recipients:',{exact:false}).waitFor();await work.getByLabel('Message',{exact:true}).fill('Service is restored and verified.');await work.getByRole('button',{name:'Send customer update'}).click();await work.waitForFunction(()=>!document.querySelector('#sheet').open);
  await work.getByRole('button',{name:'Add manual time'}).click();await work.getByLabel('Minutes worked').fill('20');await work.getByLabel('Work performed').fill('Verified the replacement firewall');await work.getByRole('button',{name:'Save time entry'}).click();await work.waitForFunction(()=>!document.querySelector('#sheet').open);const manual=writes.filter(w=>w.action==='reply'&&w.minutes).at(-1);assert.equal(manual.minutes,'20');assert.ok(manual.worked_at.endsWith('Z'),'Device timestamp lost its timezone');
  await work.getByLabel('Job section',{exact:true}).selectOption('resources');await work.getByRole('heading',{name:'People',exact:true}).waitFor();await work.getByRole('button',{name:'Branch firewall',exact:true}).click();await work.getByText('192.0.2.1 · 00:11:22:33:44:55').waitFor();await work.getByRole('button',{name:'Close',exact:true}).click();
  await work.getByRole('button',{name:'Reveal',exact:true}).click();assert.equal(await work.getByLabel('Password',{exact:true}).inputValue(),'fixture-secret-value');assert.ok(!(await work.evaluate(()=>JSON.stringify(localStorage))).includes('fixture-secret-value'));await work.getByRole('button',{name:'Close',exact:true}).click();assert.equal(await work.locator('#credential-secret').count(),0,'Closing left credential plaintext in DOM');
  await work.getByRole('button',{name:'Reveal',exact:true}).click();await work.getByLabel('Password',{exact:true}).waitFor();await work.evaluate(()=>{Object.defineProperty(document,'visibilityState',{configurable:true,value:'hidden'});document.dispatchEvent(new Event('visibilitychange'));});assert.equal(await work.locator('#credential-secret').count(),0,'Backgrounding retained credentials');await work.evaluate(()=>{Object.defineProperty(document,'visibilityState',{configurable:true,value:'visible'});document.dispatchEvent(new Event('visibilitychange'));});
  await work.getByLabel('Job section',{exact:true}).selectOption('docs');await work.getByRole('button',{name:job.documents[0].document_name}).click();await work.getByRole('button',{name:'View full document'}).click();assert.ok((await work.locator('iframe').getAttribute('src')).includes('document_view'));await work.getByRole('button',{name:'Close',exact:true}).click();
  await work.getByRole('button',{name:'Add documentation',exact:true}).click();await work.getByLabel('Document name').fill('Test site details');await work.getByLabel('Documentation',{exact:true}).fill('Record the new cabinet location.');await work.getByRole('button',{name:'Save documentation'}).click();await work.waitForFunction(()=>!document.querySelector('#sheet').open);
  await work.getByLabel('Job section',{exact:true}).selectOption('photos');await work.getByRole('button',{name:'Take a photo',exact:true}).click();assert.equal(await work.locator('#photo-form input[type=file]').getAttribute('capture'),'environment');await work.evaluate(()=>location.hash='#job/102/photos');await work.getByRole('heading',{name:'Validate the guest network',exact:true}).waitFor();await work.locator('#photo-form input[type=file]').setInputFiles({name:'fixture.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aPo0AAAAASUVORK5CYII=','base64')});await work.getByLabel('Caption',{exact:true}).fill('Field fixture photo');await work.getByRole('button',{name:'Upload photo',exact:true}).click();await work.waitForFunction(()=>!document.querySelector('#sheet').open);assert.equal(writes.filter(w=>w.action==='photo').at(-1).ticket_id,'101','Photo switched ticket while its form remained open');
  await work.getByRole('link',{name:'Find work',exact:true}).click();await work.getByRole('button',{name:'New job',exact:true}).click();await work.getByRole('textbox',{name:'Client name'}).fill('Example');await work.getByRole('button',{name:'Find client'}).click();await work.getByRole('link',{name:job.client_name,exact:true}).click();await work.getByLabel('Subject',{exact:true}).fill('Unscheduled field issue');await work.getByLabel('Work to do').fill('Investigate and document the new issue');await work.getByLabel('Job template · optional').selectOption('9');await work.getByRole('button',{name:'Create job',exact:true}).click();await work.waitForURL('**/#job/102/overview');
  await work.getByRole('button',{name:'Resolve ticket',exact:true}).click();await work.getByLabel('Resolution code').selectOption('fixed');await work.getByLabel('Resolution summary').fill('Replaced the failed component and confirmed recovery.');await work.getByRole('button',{name:'Resolve ticket',exact:true}).last().click();await work.waitForFunction(()=>!document.querySelector('#sheet').open);
  assert.equal(await work.locator('a[href^="/agent/ticket.php"],a[href^="/agent/asset.php"],a[href^="/agent/document.php"]').count(),0,'Core job links still exit to PSA');
  const safeAssetName=job.assets[0].asset_name;const unsafeLabel='<img id="injected-resource" src=x onerror="window.fixtureInjection=1">';job.assets[0].asset_name=unsafeLabel;fileLabel=unsafeLabel;
  await work.goto(base+'/agent/field/#job/101/resources');await work.getByRole('button',{name:unsafeLabel,exact:true}).waitFor();assert.equal(await work.locator('#injected-resource').count(),0,'Asset label became markup');job.assets[0].asset_name=safeAssetName;
  await work.getByLabel('Job section',{exact:true}).selectOption('photos');await work.getByRole('button',{name:unsafeLabel,exact:true}).waitFor();assert.equal(await work.locator('#injected-resource').count(),0,'Attachment label became markup');assert.equal(await work.evaluate(()=>window.fixtureInjection),undefined);fileLabel='Firewall-label.png';
  for(const width of [360,393,768,1440]){await work.setViewportSize({width,height:900});assert.equal(await work.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Workspace overflow at '+width);}
  await work.locator('#notice').waitFor({state:'hidden'});await work.setViewportSize({width:393,height:852});await work.goto(base+'/agent/field/#job/101/resources');await work.getByRole('heading',{name:'People',exact:true}).waitFor();await work.screenshot({path:path.join(screenshots,'mobile-resources.png'),fullPage:true});
  await work.goto(base+'/agent/field/#job/101/conversation');await work.getByRole('heading',{name:'Conversation and time'}).waitFor();await work.screenshot({path:path.join(screenshots,'mobile-conversation.png'),fullPage:true});
  await work.goto(base+'/agent/field/#job/101/overview');await work.getByRole('button',{name:'Manage job',exact:true}).click();await work.screenshot({path:path.join(screenshots,'mobile-manage.png'),fullPage:false});await work.getByRole('button',{name:'Close',exact:true}).click();
  await work.evaluate(()=>document.documentElement.dataset.theme='dark');await work.screenshot({path:path.join(screenshots,'mobile-dark.png'),fullPage:true});await mobile.close();
  assert.deepEqual(errors,[],'Browser JavaScript errors');
  console.log('Field browser checks passed: arrival, offline recovery, exact retry, project filtering, job management and creation, replies and time, credential privacy, documentation, and responsive layouts.');
 } finally {await browser.close();await new Promise(resolve=>server.close(resolve));}
})().catch(err=>{console.error(err);server.close();process.exitCode=1;});
